on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: jcansdale/IssuesToBlog@master
        with:
          args: push
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DOTNET_NOLOGO: true
          VIEWER_NAME: Jamie Cansdale
          VIEWER_EMAIL:  jcansdale@gmail.com
