on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: jcansdale/IssuesToBlog@master
        with:
          args: push
          secrets: ${{ github.token }}
